import type { Metadata } from 'next';
import { Vazirmatn } from 'next/font/google';
import React from 'react';

import { AppProvider } from './_providers';
import './_styles';

const vazirmatn = Vazirmatn({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
};

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface RootLayoutProps extends React.PropsWithChildren {}

const RootLayout: React.FC<RootLayoutProps> = (props) => {
  const { children } = props;

  return (
    <html lang='en'>
      <body className={`${vazirmatn.className}`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
};

export default RootLayout;
